export const ExperienceContent = [
  {
    company: "Toplyne",
    link: "https://www.nomura.com/",
    role: "Software Developer Intern",
    brief: [
      "Building a multi-tenant, scalable and flexible full stack Config Management System for the extensive configs generated by different teams to manage the workflow of the service better. Using Flask, SQL Alchemy, Alembic along with Postgres for database and Docker for DevOps. Apache Airflow for workflow management and Snowflake for data warehousing.",
      "Toplyne is the tool used by Canva, Grafana, Gather.Town, InVideo and LambdaTest to identify which of their free users/accounts are ready for a premium subscription, and which of their paid/user accounts are ready for larger plans. Toplyne helps you find your product-qualified leads by combining your existing data sources and gets them in your CRM systems."
    ],
  },
  {
    company: "Nomura Holdings",
    link: "https://www.nomura.com/",
    role: "Software Developer Intern",
    brief: [
      "Developed a Feed Generator in Java Springboot along with utility classes and functions for data retrieval,filtering, and congregation into excel to generate a report based on given filter criteria and reduce manual effort by 90%",
      "Composed UNIX scripts and accelerated the data warehousing pipeline by automating the processes feed generations, packaging them with respective check-sums and .info files and publishing them to a central data warehouse.",
      "Mastered multiple tools in the Java application development and deployment pipeline, including package management using Maven, Testing using Jconsole, Versioning using Git and building using Jenkins.",
      "Developed a ReactJS frontend for an Automation as a Service (AaaS) application developed on Java to handle automated testing using the RobotFramework, reducing manual effort and redundancy.",
      "Created Natural Language Processing (SBERT) pipeline in Python along with MS excel to find similarity indexes through multiple sentence encoding algorithms and aggregate similar responses to business life cycle events to reduce duplication in controls across different regions and business units by 60%.",
    ],
  },
  {
    company: "Bitglaze Technologies",
    link: "https://www.linkedin.com/company/bitglaze-technologies/",
    role: "Web App Developer Intern",
    brief: [
      "Collaborated as a Full Stack Web Developer to design an Enterprise Resource Planning System with databases and implemented API(s) for multiple integrated modules such as Core (Departments, Designations, Employees management), Attendances, Leaves using PostgreSQL Django Rest Framework.",
      "Designed a custom renderer and parser for JSON objects for much improved data visualization and handling.",
      "Introduced MPTT to incorporate hierarchical models. Designed a custom backend filter for 30% efficient selective retrieval of data. Built Celery tasks for automation of tasks like leave generation and leave handling.",
      "Dockerized entire project to enable cross platform deployment and consistency.",
      "Generated Postman and Swagger API specs for easy testing and handling.",
      "Documented entire module in overleaf using LaTeX for trouble free handover.",
    ],
  },
];
